#!/bin/bash


if [ -z "$1" ] || [ -z "$2" ]
then
    echo "$0 <text file> <pattern file>"
    exit
fi


textFile=$1
patternFile=$2

declare -a implementations=(
    # "-p h -n 0 -e 0"
    "-p s -n 0 -e 0"
    # "-p n -n 0 -e 0"
    # "-p p -n 1 -e 0"
    "-p p -n 2 -e 0"
    # "-p p -n 3 -e 0"
    # "-p p -n 4 -e 0"
    # # "-p m -n 0 -e 0"
    # # "-p m -n 0 -e 1"
    # "-p m -n 0 -e 2"
    # # "-p m -n 0 -e 3"
    # # "-p m -n 0 -e 4"
    # # "-p m -n 0 -e 5"
)


# "s" "n" "s" "n")

RootDir=data
mkdir -p $RootDir

while read line_content; do
    for p in "${implementations[@]}"
    do
	output=$(./tp4 -i $textFile  $p  -t $line_content -s -d)
	numOfCharsFile=$(wc -c $textFile | awk '{print $1}')
	numOfCharsPattern=${#line_content}
	execArgs=$(echo "$p" | awk '{print $4" "$6}')
	Implementation=$(echo "$p" | awk '{print $2}')
	Comparations=$(echo "$output" | awk '/Comparations/{print $2}')
	totalAndRealTime=$(echo "$output" | awk '/Total Time/{print $9 $12}'| grep -o '[0-9]\+.[0-9]\+')
	echo "$Implementation $numOfCharsFile $numOfCharsPattern" $totalAndRealTime "$execArgs $Comparations">> "$RootDir/""data.txt"
    done
done < $patternFile
